notifications:
  slack:
    rooms:
      - trifork-se:rsjWCAsE47JsZYbFNzPpjbnM
    template:
      - "Build %{result} from %{author} (#%{build_number} %{branch}, %{commit}) %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
language: node_js
node_js:
  - "node"
before_script:
  - make install
script:
  - make test
