notifications:
  slack:
    rooms:
      - trifork-se:rsjWCAsE47JsZYbFNzPpjbnM
    template:
      - "Build ${result} from ${author} (${branch}, ${commit_message}, ${commit})"
language: node_js
node_js:
  - "node"
before_script:
  - make setup
script:
  - make test
