notifications:
  template: "Build ${result} from ${author} (${branch}, ${commit_message}, ${commit})"
  slack: trifork-se:rsjWCAsE47JsZYbFNzPpjbnM
language: node_js
node_js:
  - "node"
before_script:
  - make setup
script:
  - make test
